/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Background: typeof import('./components/Background.vue')['default']
    ContentSettings: typeof import('./components/ContentSettings.vue')['default']
    DevSet: typeof import('./components/DevSet.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./components/Footer.vue')['default']
    Hitokoto: typeof import('./components/Hitokoto.vue')['default']
    Links: typeof import('./components/Links.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    Message: typeof import('./components/Message.vue')['default']
    MoreContent: typeof import('./components/MoreContent.vue')['default']
    Music: typeof import('./components/Music.vue')['default']
    OwnerPanel: typeof import('./components/OwnerPanel.vue')['default']
    Player: typeof import('./components/Player.vue')['default']
    PlayerSeekBar: typeof import('./components/PlayerSeekBar.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    SecuritySettings: typeof import('./components/SecuritySettings.vue')['default']
    Set: typeof import('./components/Set.vue')['default']
    SocialLinks: typeof import('./components/SocialLinks.vue')['default']
    ThemeSwitcher: typeof import('./components/ThemeSwitcher.vue')['default']
    TimeCapsule: typeof import('./components/TimeCapsule.vue')['default']
    VolumeSlider: typeof import('./components/VolumeSlider.vue')['default']
    Weather: typeof import('./components/Weather.vue')['default']
  }
}
