export type PlayerStatus = "idle" | "loading" | "ready" | "playing" | "paused" | "error";
export type BackgroundEffect = "snow" | "firefly" | "lantern" | "meteor";
export type BackgroundEffectMode = "auto" | "off" | "manual";
export type ThemePreference = "system" | "time" | "light" | "dark";

export interface MainState {
    imgLoadStatus: boolean;
    innerWidth: number | null;
    musicBoxOpenState: boolean;
    musicIsOk: boolean;
    musicVolume: number;
    boxOpenState: boolean;
    mobileOpenState: boolean;
    mobileFuncState: boolean;
    playerStatus: PlayerStatus;
    playerHasStarted: boolean;
    playerError: string | null;
    playerCanplay: boolean;
    playerTitle: string | null;
    playerArtist: string | null;
    playerAlbum: string | null;
    playerLyric: string;
    footerPlayerShow: boolean;
    playerOrder: "list" | "single" | "shuffle";
    playerCurrentTime: number;
    playerDuration: number;
    showFirefly: boolean;
    showSnowfall: boolean;
    showLantern: boolean;
    showMeteor: boolean;
};
