import type { WeatherLocation } from "@/typings/weather";

export type PlayerStatus = "idle" | "loading" | "ready" | "playing" | "paused" | "error";
export type BackgroundEffect = "snow" | "firefly" | "lantern" | "meteor";
export type BackgroundEffectMode = "auto" | "off" | "manual";

export interface MainState {
    imgLoadStatus: boolean;
    innerWidth: number | null;
    coverType: number;
    sBGCount: string | null;
    autoBGSwitchInterval : number;
    wallpaperLocalId: number | null;
    wallpaperMaxId: number;
    effectsMode: BackgroundEffectMode;
    selectedEffects: BackgroundEffect[];
    msgNameShow: boolean;
    siteStartShow: boolean;
    musicBoxOpenState: boolean;
    musicIsOk: boolean;
    musicVolume: number;
    backgroundShow: boolean;
    boxOpenState: boolean;
    mobileOpenState: boolean;
    mobileFuncState: boolean;
    setV: boolean;
    playerStatus: PlayerStatus;
    playerHasStarted: boolean;
    playerError: string | null;
    playerCanplay: boolean;
    playerTitle: string | null;
    playerArtist: string | null;
    playerAlbum: string | null;
    playerLyric: string;
    footerPlayerShow: boolean;
    footerBlur: boolean;
    playerAutoplay: boolean;
    playerOrder: "list" | "single" | "shuffle";
    playerKeyboardShortcuts: boolean;
    weatherLocation: WeatherLocation | null;
    playerCurrentTime: number;
    playerDuration: number;
    showFirefly: boolean;
    showSnowfall: boolean;
    showLantern: boolean;
    showMeteor: boolean;
    theme: "system" | "time" | "bg" | "light" | "dark";
};
